# coding: utf-8

"""
    GoCardless Bank Account Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0 (v2)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gocardless_bankaccountdata
from gocardless_bankaccountdata.api.agreements_api import AgreementsApi  # noqa: E501
from gocardless_bankaccountdata.rest import ApiException


class TestAgreementsApi(unittest.TestCase):
    """AgreementsApi unit test stubs"""

    def setUp(self):
        self.api = AgreementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_eua(self):
        """Test case for accept_eua

        """
        pass

    def test_create_eua(self):
        """Test case for create_eua

        """
        pass

    def test_delete_eua_by_id(self):
        """Test case for delete_eua_by_id

        """
        pass

    def test_retrieve_all_euas_for_an_end_user(self):
        """Test case for retrieve_all_euas_for_an_end_user

        """
        pass

    def test_retrieve_eua_by_id(self):
        """Test case for retrieve_eua_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
