# coding: utf-8

"""
    GoCardless Bank Account Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0 (v2)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gocardless_bankaccountdata
from gocardless_bankaccountdata.api.token_api import TokenApi  # noqa: E501
from gocardless_bankaccountdata.rest import ApiException


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self):
        self.api = TokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_a_new_access_token(self):
        """Test case for get_a_new_access_token

        """
        pass

    def test_obtain_new_accessrefresh_token_pair(self):
        """Test case for obtain_new_accessrefresh_token_pair

        """
        pass


if __name__ == '__main__':
    unittest.main()
