# coding: utf-8

"""
    GoCardless Bank Account Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0 (v2)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gocardless_bankaccountdata
from gocardless_bankaccountdata.models.gocardless_bankaccountdata_enduser_acceptance_details_request import GocardlessBankaccountdataEnduserAcceptanceDetailsRequest  # noqa: E501
from gocardless_bankaccountdata.rest import ApiException


class TestGocardlessBankaccountdataEnduserAcceptanceDetailsRequest(unittest.TestCase):
    """GocardlessBankaccountdataEnduserAcceptanceDetailsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGocardlessBankaccountdataEnduserAcceptanceDetailsRequest(self):
        """Test GocardlessBankaccountdataEnduserAcceptanceDetailsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gocardless_bankaccountdata.models.gocardless_bankaccountdata_enduser_acceptance_details_request.GocardlessBankaccountdataEnduserAcceptanceDetailsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
