# coding: utf-8

"""
    GoCardless Bank Account Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0 (v2)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GocardlessBankaccountdataEndUserAgreementRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'institution_id': 'str',
        'max_historical_days': 'int',
        'access_valid_for_days': 'int',
        'access_scope': 'list[object]'
    }

    attribute_map = {
        'institution_id': 'institution_id',
        'max_historical_days': 'max_historical_days',
        'access_valid_for_days': 'access_valid_for_days',
        'access_scope': 'access_scope'
    }

    def __init__(self, institution_id=None, max_historical_days=90, access_valid_for_days=90, access_scope=None):  # noqa: E501
        """GocardlessBankaccountdataEndUserAgreementRequest - a model defined in Swagger"""  # noqa: E501
        self._institution_id = None
        self._max_historical_days = None
        self._access_valid_for_days = None
        self._access_scope = None
        self.discriminator = None
        self.institution_id = institution_id
        if max_historical_days is not None:
            self.max_historical_days = max_historical_days
        if access_valid_for_days is not None:
            self.access_valid_for_days = access_valid_for_days
        if access_scope is not None:
            self.access_scope = access_scope

    @property
    def institution_id(self):
        """Gets the institution_id of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501

        an Institution ID for this EUA  # noqa: E501

        :return: The institution_id of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501
        :rtype: str
        """
        return self._institution_id

    @institution_id.setter
    def institution_id(self, institution_id):
        """Sets the institution_id of this GocardlessBankaccountdataEndUserAgreementRequest.

        an Institution ID for this EUA  # noqa: E501

        :param institution_id: The institution_id of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501
        :type: str
        """
        if institution_id is None:
            raise ValueError("Invalid value for `institution_id`, must not be `None`")  # noqa: E501

        self._institution_id = institution_id

    @property
    def max_historical_days(self):
        """Gets the max_historical_days of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501

        Maximum number of days of transaction data to retrieve.  # noqa: E501

        :return: The max_historical_days of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501
        :rtype: int
        """
        return self._max_historical_days

    @max_historical_days.setter
    def max_historical_days(self, max_historical_days):
        """Sets the max_historical_days of this GocardlessBankaccountdataEndUserAgreementRequest.

        Maximum number of days of transaction data to retrieve.  # noqa: E501

        :param max_historical_days: The max_historical_days of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501
        :type: int
        """

        self._max_historical_days = max_historical_days

    @property
    def access_valid_for_days(self):
        """Gets the access_valid_for_days of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501

        Number of days from acceptance that the access can be used.  # noqa: E501

        :return: The access_valid_for_days of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501
        :rtype: int
        """
        return self._access_valid_for_days

    @access_valid_for_days.setter
    def access_valid_for_days(self, access_valid_for_days):
        """Sets the access_valid_for_days of this GocardlessBankaccountdataEndUserAgreementRequest.

        Number of days from acceptance that the access can be used.  # noqa: E501

        :param access_valid_for_days: The access_valid_for_days of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501
        :type: int
        """

        self._access_valid_for_days = access_valid_for_days

    @property
    def access_scope(self):
        """Gets the access_scope of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501

        Array containing one or several values of ['balances', 'details', 'transactions']  # noqa: E501

        :return: The access_scope of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501
        :rtype: list[object]
        """
        return self._access_scope

    @access_scope.setter
    def access_scope(self, access_scope):
        """Sets the access_scope of this GocardlessBankaccountdataEndUserAgreementRequest.

        Array containing one or several values of ['balances', 'details', 'transactions']  # noqa: E501

        :param access_scope: The access_scope of this GocardlessBankaccountdataEndUserAgreementRequest.  # noqa: E501
        :type: list[object]
        """

        self._access_scope = access_scope

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GocardlessBankaccountdataEndUserAgreementRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GocardlessBankaccountdataEndUserAgreementRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
