# coding: utf-8

"""
    GoCardless Bank Account Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0 (v2)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GocardlessBankaccountdataAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'created': 'datetime',
        'last_accessed': 'datetime',
        'iban': 'str',
        'bban': 'str',
        'status': 'str',
        'institution_id': 'str',
        'owner_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'created': 'created',
        'last_accessed': 'last_accessed',
        'iban': 'iban',
        'bban': 'bban',
        'status': 'status',
        'institution_id': 'institution_id',
        'owner_name': 'owner_name'
    }

    def __init__(self, id=None, created=None, last_accessed=None, iban=None, bban=None, status=None, institution_id=None, owner_name=None):  # noqa: E501
        """GocardlessBankaccountdataAccount - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._created = None
        self._last_accessed = None
        self._iban = None
        self._bban = None
        self._status = None
        self._institution_id = None
        self._owner_name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if created is not None:
            self.created = created
        if last_accessed is not None:
            self.last_accessed = last_accessed
        if iban is not None:
            self.iban = iban
        if bban is not None:
            self.bban = bban
        if status is not None:
            self.status = status
        if institution_id is not None:
            self.institution_id = institution_id
        if owner_name is not None:
            self.owner_name = owner_name

    @property
    def id(self):
        """Gets the id of this GocardlessBankaccountdataAccount.  # noqa: E501

        The ID of this Account, used to refer to this account in other API calls.  # noqa: E501

        :return: The id of this GocardlessBankaccountdataAccount.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GocardlessBankaccountdataAccount.

        The ID of this Account, used to refer to this account in other API calls.  # noqa: E501

        :param id: The id of this GocardlessBankaccountdataAccount.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def created(self):
        """Gets the created of this GocardlessBankaccountdataAccount.  # noqa: E501

        The date & time at which the account object was created.  # noqa: E501

        :return: The created of this GocardlessBankaccountdataAccount.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this GocardlessBankaccountdataAccount.

        The date & time at which the account object was created.  # noqa: E501

        :param created: The created of this GocardlessBankaccountdataAccount.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def last_accessed(self):
        """Gets the last_accessed of this GocardlessBankaccountdataAccount.  # noqa: E501

        The date & time at which the account object was last accessed.  # noqa: E501

        :return: The last_accessed of this GocardlessBankaccountdataAccount.  # noqa: E501
        :rtype: datetime
        """
        return self._last_accessed

    @last_accessed.setter
    def last_accessed(self, last_accessed):
        """Sets the last_accessed of this GocardlessBankaccountdataAccount.

        The date & time at which the account object was last accessed.  # noqa: E501

        :param last_accessed: The last_accessed of this GocardlessBankaccountdataAccount.  # noqa: E501
        :type: datetime
        """

        self._last_accessed = last_accessed

    @property
    def iban(self):
        """Gets the iban of this GocardlessBankaccountdataAccount.  # noqa: E501

        The Account IBAN  # noqa: E501

        :return: The iban of this GocardlessBankaccountdataAccount.  # noqa: E501
        :rtype: str
        """
        return self._iban

    @iban.setter
    def iban(self, iban):
        """Sets the iban of this GocardlessBankaccountdataAccount.

        The Account IBAN  # noqa: E501

        :param iban: The iban of this GocardlessBankaccountdataAccount.  # noqa: E501
        :type: str
        """

        self._iban = iban

    @property
    def bban(self):
        """Gets the bban of this GocardlessBankaccountdataAccount.  # noqa: E501

        The Account BBAN  # noqa: E501

        :return: The bban of this GocardlessBankaccountdataAccount.  # noqa: E501
        :rtype: str
        """
        return self._bban

    @bban.setter
    def bban(self, bban):
        """Sets the bban of this GocardlessBankaccountdataAccount.

        The Account BBAN  # noqa: E501

        :param bban: The bban of this GocardlessBankaccountdataAccount.  # noqa: E501
        :type: str
        """

        self._bban = bban

    @property
    def status(self):
        """Gets the status of this GocardlessBankaccountdataAccount.  # noqa: E501

        The processing status of this account.  # noqa: E501

        :return: The status of this GocardlessBankaccountdataAccount.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this GocardlessBankaccountdataAccount.

        The processing status of this account.  # noqa: E501

        :param status: The status of this GocardlessBankaccountdataAccount.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def institution_id(self):
        """Gets the institution_id of this GocardlessBankaccountdataAccount.  # noqa: E501

        The ASPSP associated with this account.  # noqa: E501

        :return: The institution_id of this GocardlessBankaccountdataAccount.  # noqa: E501
        :rtype: str
        """
        return self._institution_id

    @institution_id.setter
    def institution_id(self, institution_id):
        """Sets the institution_id of this GocardlessBankaccountdataAccount.

        The ASPSP associated with this account.  # noqa: E501

        :param institution_id: The institution_id of this GocardlessBankaccountdataAccount.  # noqa: E501
        :type: str
        """

        self._institution_id = institution_id

    @property
    def owner_name(self):
        """Gets the owner_name of this GocardlessBankaccountdataAccount.  # noqa: E501

        The name of the account owner.  # noqa: E501

        :return: The owner_name of this GocardlessBankaccountdataAccount.  # noqa: E501
        :rtype: str
        """
        return self._owner_name

    @owner_name.setter
    def owner_name(self, owner_name):
        """Sets the owner_name of this GocardlessBankaccountdataAccount.

        The name of the account owner.  # noqa: E501

        :param owner_name: The owner_name of this GocardlessBankaccountdataAccount.  # noqa: E501
        :type: str
        """

        self._owner_name = owner_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GocardlessBankaccountdataAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GocardlessBankaccountdataAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
