# coding: utf-8

"""
    GoCardless Bank Account Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0 (v2)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GocardlessBankaccountdataOwnerAddressStructuredSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'street_name': 'str',
        'building_number': 'str',
        'town_name': 'str',
        'post_code': 'str',
        'country': 'str'
    }

    attribute_map = {
        'street_name': 'streetName',
        'building_number': 'buildingNumber',
        'town_name': 'townName',
        'post_code': 'postCode',
        'country': 'country'
    }

    def __init__(self, street_name=None, building_number=None, town_name=None, post_code=None, country=None):  # noqa: E501
        """GocardlessBankaccountdataOwnerAddressStructuredSchema - a model defined in Swagger"""  # noqa: E501
        self._street_name = None
        self._building_number = None
        self._town_name = None
        self._post_code = None
        self._country = None
        self.discriminator = None
        if street_name is not None:
            self.street_name = street_name
        if building_number is not None:
            self.building_number = building_number
        if town_name is not None:
            self.town_name = town_name
        if post_code is not None:
            self.post_code = post_code
        if country is not None:
            self.country = country

    @property
    def street_name(self):
        """Gets the street_name of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501

        streetName  # noqa: E501

        :return: The street_name of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :rtype: str
        """
        return self._street_name

    @street_name.setter
    def street_name(self, street_name):
        """Sets the street_name of this GocardlessBankaccountdataOwnerAddressStructuredSchema.

        streetName  # noqa: E501

        :param street_name: The street_name of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :type: str
        """

        self._street_name = street_name

    @property
    def building_number(self):
        """Gets the building_number of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501

        buildingNumber  # noqa: E501

        :return: The building_number of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :rtype: str
        """
        return self._building_number

    @building_number.setter
    def building_number(self, building_number):
        """Sets the building_number of this GocardlessBankaccountdataOwnerAddressStructuredSchema.

        buildingNumber  # noqa: E501

        :param building_number: The building_number of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :type: str
        """

        self._building_number = building_number

    @property
    def town_name(self):
        """Gets the town_name of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501

        townName  # noqa: E501

        :return: The town_name of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :rtype: str
        """
        return self._town_name

    @town_name.setter
    def town_name(self, town_name):
        """Sets the town_name of this GocardlessBankaccountdataOwnerAddressStructuredSchema.

        townName  # noqa: E501

        :param town_name: The town_name of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :type: str
        """

        self._town_name = town_name

    @property
    def post_code(self):
        """Gets the post_code of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501

        postCode  # noqa: E501

        :return: The post_code of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :rtype: str
        """
        return self._post_code

    @post_code.setter
    def post_code(self, post_code):
        """Sets the post_code of this GocardlessBankaccountdataOwnerAddressStructuredSchema.

        postCode  # noqa: E501

        :param post_code: The post_code of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :type: str
        """

        self._post_code = post_code

    @property
    def country(self):
        """Gets the country of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501

        country  # noqa: E501

        :return: The country of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this GocardlessBankaccountdataOwnerAddressStructuredSchema.

        country  # noqa: E501

        :param country: The country of this GocardlessBankaccountdataOwnerAddressStructuredSchema.  # noqa: E501
        :type: str
        """

        self._country = country

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GocardlessBankaccountdataOwnerAddressStructuredSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GocardlessBankaccountdataOwnerAddressStructuredSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
