# coding: utf-8

"""
    GoCardless Bank Account Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0 (v2)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GocardlessBankaccountdataErrorResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'summary': 'str',
        'detail': 'str',
        'type': 'str',
        'status_code': 'int'
    }

    attribute_map = {
        'summary': 'summary',
        'detail': 'detail',
        'type': 'type',
        'status_code': 'status_code'
    }

    def __init__(self, summary=None, detail=None, type=None, status_code=None):  # noqa: E501
        """GocardlessBankaccountdataErrorResponse - a model defined in Swagger"""  # noqa: E501
        self._summary = None
        self._detail = None
        self._type = None
        self._status_code = None
        self.discriminator = None
        self.summary = summary
        self.detail = detail
        if type is not None:
            self.type = type
        self.status_code = status_code

    @property
    def summary(self):
        """Gets the summary of this GocardlessBankaccountdataErrorResponse.  # noqa: E501


        :return: The summary of this GocardlessBankaccountdataErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this GocardlessBankaccountdataErrorResponse.


        :param summary: The summary of this GocardlessBankaccountdataErrorResponse.  # noqa: E501
        :type: str
        """
        if summary is None:
            raise ValueError("Invalid value for `summary`, must not be `None`")  # noqa: E501

        self._summary = summary

    @property
    def detail(self):
        """Gets the detail of this GocardlessBankaccountdataErrorResponse.  # noqa: E501


        :return: The detail of this GocardlessBankaccountdataErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this GocardlessBankaccountdataErrorResponse.


        :param detail: The detail of this GocardlessBankaccountdataErrorResponse.  # noqa: E501
        :type: str
        """
        if detail is None:
            raise ValueError("Invalid value for `detail`, must not be `None`")  # noqa: E501

        self._detail = detail

    @property
    def type(self):
        """Gets the type of this GocardlessBankaccountdataErrorResponse.  # noqa: E501


        :return: The type of this GocardlessBankaccountdataErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GocardlessBankaccountdataErrorResponse.


        :param type: The type of this GocardlessBankaccountdataErrorResponse.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def status_code(self):
        """Gets the status_code of this GocardlessBankaccountdataErrorResponse.  # noqa: E501


        :return: The status_code of this GocardlessBankaccountdataErrorResponse.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this GocardlessBankaccountdataErrorResponse.


        :param status_code: The status_code of this GocardlessBankaccountdataErrorResponse.  # noqa: E501
        :type: int
        """
        if status_code is None:
            raise ValueError("Invalid value for `status_code`, must not be `None`")  # noqa: E501

        self._status_code = status_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GocardlessBankaccountdataErrorResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GocardlessBankaccountdataErrorResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
