# coding: utf-8

"""
    GoCardless Bank Account Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0 (v2)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GocardlessBankaccountdataSpectacularJWTRefresh(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access': 'str',
        'access_expires': 'int'
    }

    attribute_map = {
        'access': 'access',
        'access_expires': 'access_expires'
    }

    def __init__(self, access=None, access_expires=86400):  # noqa: E501
        """GocardlessBankaccountdataSpectacularJWTRefresh - a model defined in Swagger"""  # noqa: E501
        self._access = None
        self._access_expires = None
        self.discriminator = None
        if access is not None:
            self.access = access
        if access_expires is not None:
            self.access_expires = access_expires

    @property
    def access(self):
        """Gets the access of this GocardlessBankaccountdataSpectacularJWTRefresh.  # noqa: E501

        Your access token  # noqa: E501

        :return: The access of this GocardlessBankaccountdataSpectacularJWTRefresh.  # noqa: E501
        :rtype: str
        """
        return self._access

    @access.setter
    def access(self, access):
        """Sets the access of this GocardlessBankaccountdataSpectacularJWTRefresh.

        Your access token  # noqa: E501

        :param access: The access of this GocardlessBankaccountdataSpectacularJWTRefresh.  # noqa: E501
        :type: str
        """

        self._access = access

    @property
    def access_expires(self):
        """Gets the access_expires of this GocardlessBankaccountdataSpectacularJWTRefresh.  # noqa: E501

        Access token expires in seconds  # noqa: E501

        :return: The access_expires of this GocardlessBankaccountdataSpectacularJWTRefresh.  # noqa: E501
        :rtype: int
        """
        return self._access_expires

    @access_expires.setter
    def access_expires(self, access_expires):
        """Sets the access_expires of this GocardlessBankaccountdataSpectacularJWTRefresh.

        Access token expires in seconds  # noqa: E501

        :param access_expires: The access_expires of this GocardlessBankaccountdataSpectacularJWTRefresh.  # noqa: E501
        :type: int
        """

        self._access_expires = access_expires

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GocardlessBankaccountdataSpectacularJWTRefresh, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GocardlessBankaccountdataSpectacularJWTRefresh):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
