# coding: utf-8

"""
    GoCardless Bank Account Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0 (v2)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GocardlessBankaccountdataSpectacularJWTObtain(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access': 'str',
        'access_expires': 'int',
        'refresh': 'str',
        'refresh_expires': 'int'
    }

    attribute_map = {
        'access': 'access',
        'access_expires': 'access_expires',
        'refresh': 'refresh',
        'refresh_expires': 'refresh_expires'
    }

    def __init__(self, access=None, access_expires=86400, refresh=None, refresh_expires=2592000):  # noqa: E501
        """GocardlessBankaccountdataSpectacularJWTObtain - a model defined in Swagger"""  # noqa: E501
        self._access = None
        self._access_expires = None
        self._refresh = None
        self._refresh_expires = None
        self.discriminator = None
        if access is not None:
            self.access = access
        if access_expires is not None:
            self.access_expires = access_expires
        if refresh is not None:
            self.refresh = refresh
        if refresh_expires is not None:
            self.refresh_expires = refresh_expires

    @property
    def access(self):
        """Gets the access of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501

        Your access token  # noqa: E501

        :return: The access of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501
        :rtype: str
        """
        return self._access

    @access.setter
    def access(self, access):
        """Sets the access of this GocardlessBankaccountdataSpectacularJWTObtain.

        Your access token  # noqa: E501

        :param access: The access of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501
        :type: str
        """

        self._access = access

    @property
    def access_expires(self):
        """Gets the access_expires of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501

        Access token expires in seconds  # noqa: E501

        :return: The access_expires of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501
        :rtype: int
        """
        return self._access_expires

    @access_expires.setter
    def access_expires(self, access_expires):
        """Sets the access_expires of this GocardlessBankaccountdataSpectacularJWTObtain.

        Access token expires in seconds  # noqa: E501

        :param access_expires: The access_expires of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501
        :type: int
        """

        self._access_expires = access_expires

    @property
    def refresh(self):
        """Gets the refresh of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501

        Your refresh token  # noqa: E501

        :return: The refresh of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501
        :rtype: str
        """
        return self._refresh

    @refresh.setter
    def refresh(self, refresh):
        """Sets the refresh of this GocardlessBankaccountdataSpectacularJWTObtain.

        Your refresh token  # noqa: E501

        :param refresh: The refresh of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501
        :type: str
        """

        self._refresh = refresh

    @property
    def refresh_expires(self):
        """Gets the refresh_expires of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501

        Refresh token expires in seconds  # noqa: E501

        :return: The refresh_expires of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501
        :rtype: int
        """
        return self._refresh_expires

    @refresh_expires.setter
    def refresh_expires(self, refresh_expires):
        """Sets the refresh_expires of this GocardlessBankaccountdataSpectacularJWTObtain.

        Refresh token expires in seconds  # noqa: E501

        :param refresh_expires: The refresh_expires of this GocardlessBankaccountdataSpectacularJWTObtain.  # noqa: E501
        :type: int
        """

        self._refresh_expires = refresh_expires

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GocardlessBankaccountdataSpectacularJWTObtain, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GocardlessBankaccountdataSpectacularJWTObtain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
